// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: api/comm/v1/comm.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gtr_Translate_FullMethodName = "/Gtr/Translate"
)

// GtrClient is the client API for Gtr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GtrClient interface {
	// ServerStream
	Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TranslateResponse], error)
}

type gtrClient struct {
	cc grpc.ClientConnInterface
}

func NewGtrClient(cc grpc.ClientConnInterface) GtrClient {
	return &gtrClient{cc}
}

func (c *gtrClient) Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TranslateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gtr_ServiceDesc.Streams[0], Gtr_Translate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranslateRequest, TranslateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gtr_TranslateClient = grpc.ServerStreamingClient[TranslateResponse]

// GtrServer is the server API for Gtr service.
// All implementations must embed UnimplementedGtrServer
// for forward compatibility.
type GtrServer interface {
	// ServerStream
	Translate(*TranslateRequest, grpc.ServerStreamingServer[TranslateResponse]) error
	mustEmbedUnimplementedGtrServer()
}

// UnimplementedGtrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGtrServer struct{}

func (UnimplementedGtrServer) Translate(*TranslateRequest, grpc.ServerStreamingServer[TranslateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Translate not implemented")
}
func (UnimplementedGtrServer) mustEmbedUnimplementedGtrServer() {}
func (UnimplementedGtrServer) testEmbeddedByValue()             {}

// UnsafeGtrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GtrServer will
// result in compilation errors.
type UnsafeGtrServer interface {
	mustEmbedUnimplementedGtrServer()
}

func RegisterGtrServer(s grpc.ServiceRegistrar, srv GtrServer) {
	// If the following call pancis, it indicates UnimplementedGtrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gtr_ServiceDesc, srv)
}

func _Gtr_Translate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TranslateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GtrServer).Translate(m, &grpc.GenericServerStream[TranslateRequest, TranslateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gtr_TranslateServer = grpc.ServerStreamingServer[TranslateResponse]

// Gtr_ServiceDesc is the grpc.ServiceDesc for Gtr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gtr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Gtr",
	HandlerType: (*GtrServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Translate",
			Handler:       _Gtr_Translate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/comm/v1/comm.proto",
}
